language: ruby

#cache: bundler


env:
  global:
    # Doctr deploy key for melund/melund.github.io
    - secure: "QS0FM3Ujfo8BZkLKFzj77zqMNrdcBI8E/QKm9rG28fQxow5dXl1jNwpwha7D+y+I5qwb8fntVFPJsg4ibW2YROtICMZ0srFZejCorDEUey6aZOPsNrhVvuo3ZJVd1VNLUosz1M1gT2xnkCTQvrXMCzec4tgPJ0WsIUu4m9KjIv5OZ0PvIZ0vFHjgsmKwHLp3egGlM0vmcvOOdov3+ukT2m7BcabD2iIezsqAzC/Kb1oR0WVYC27q0b+afponJS+u5NtopFwKBWGxb9ssc/d2G7zE7qPTf8GewJfKzDW0laKwUcMpUEfzJzf2/IoIVhsTQ+K1ANH0O+dsZKOzeTeUeR8r7gb5mGKnlbXF+q2U+S2ubQdbjAxPp2ksAGqSKhzo+wyxe0mYu9y+xC6qiY/+ZanqcdCdj7rdW9XGYNp6Kfvbp8Dv+/1JXVz3KlTTy8XYzLvt+TVqQD69B7T7wkv7VL0RYD+f6+JWsI69pnyItt2BRPxr4JsG9qUr9dVyhbfKW9PMdDatFmcvn8z7Sk68vyJN3AnyVhtLbEsRKrgud/pW43VJB2eibAJTSzjbSvmpXgFA+wXPRJPcBuco5kU5adV6TvB135EsiZdq2f5vxSuUBHCpX1t+9okABcbnbZOQZ1H3dsCTmiJNdburcFNSjXtmNWWXrfAZgAIMCahxz0Y="
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge # For sphinxcontrib.autoprogram
  - conda update -q conda
  - conda info -a
  - conda create -q -n deploy-environment python=3.6 doctr 
  - conda create -q -n build-environment python=2.7 pygments_anyscript 
  - source activate build-environment
  - gem install pygments.rb minimal-mistakes-jekyll jekyll
#  - bundle install

before_script:
  - rvm get head || true

script:
  - set -e
  - jekyll build --verbose
  #- htmlproofer --alt-ignore '/.*/' ./_site
  - source activate deploy-environment
  - doctr deploy --built-docs ./_site --deploy-branch-name master --deploy-repo AnyBody/anybody.github.io .;


sudo: false # route your build to the container-based infrastructure for a faster build
