language: ruby

cache: bundler


env:
  global:
    # Doctr deploy key for melund/anyscript_test
    - secure: "nTpTm19nQWJ1P1i/fu47eEKd/B4WOlGtHbntoD27kWyUb+32WOva0iPWlWlJPSrGaJ6BOxT2brKuUSyNC/5GbQ+tiyKIBR6x+G6fDB9H55zwMgVRIp+aTe1Z41y7lQW/E2SYyetJVXfEk0TUJRsakuaBkpOQjBek67ncAu0mMCHM76Z4s08Xx7IxdshtQxEwdkMl+thsuQdzugQ9gw/aY16JZjTUZGJKu+2M08QAkCbJ1I1PIJ9Nr7o7rSEpMZoPev+m8Wyel2KiNxYeGeAxrn3i5BWzk0tD6aBs3l+WKhdeYV1ALxczbmyG6yX9HXkHX+HCHcbUcHdX11VK5X/1ZCOS7illSMoIht+Aj8XzxWlJgX17htn7vEBfSR+6J1/V4U8MChFNy7gxOTK4OlHIm+bt5II20tUjKphSp7naaSnTARumi+CcZXXMKDFkyylJViNVgrgnfSEcLOxSSLazScnQN98V8+dIy0LHMnRPBRiSZtkIK15ih59wCd+0RuIj2Mt+rNZsKKtJPK9d4tUF5ksRG6tUpDm/7DrU4hdEflEG9MxO6WGsFa/tTLKHtX8lo4at2m8phN+wIa51X/Yud8uhi9Bu7hXW5JFiUpWEIAMSexyizD828OlAL/w1JWTnvLBi+CQiP6IUUq2GQZVI6g9Gwl94n6sLXC6Wlqivloo="
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

install:
  - gem install bundler
  - bundle install
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge # For sphinxcontrib.autoprogram
  - conda update -q conda
  - conda info -a
  - conda create -q -n doc-build-environment python=3.6 doctr pygments_anyscript

before_script:
  - rvm get head || true

script:
  - set -e
  - bundle exec jekyll build
  - htmlproofer ./_site
  - source activate doc-build-environment
  - doctr deploy --built-docs ./_site --deploy-branch-name master --deploy-repo melund/anyscript_test .;


sudo: false # route your build to the container-based infrastructure for a faster build
