# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en"
title                    : "AnyScript Community"
title_separator          : "-"
name                     : "AnyBody Technology A/S"
description              : "A community for the users of AnyBody Modeling System and the AnyScript language."
url                      : "https://anyscript.org"
#baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "AnyBody/anyscript"
teaser                   : "/assets/images/teaser.jpg"
logo                     : "/assets/images/anyscript_logo.svg"
masthead_title           : " "


# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "discourse"
  discourse:
    server               : "forum.anyscript.org"
reCaptcha:
  siteKey                : "6Lfw4lwUAAAAAGl9_h1wU0-i0njA9phbqKKLLyT-"
  secret                 : "Kk9T7TyxNwsutSdQIgfLAFMPAM/rWcJjM4xCVRzk2kvNBaDfzykywZgp0dzowWfyBzlL5AxzRY40iGZHPKaNJ9az2ZPWL0J+eWR1w3CqGS/noRh6Ty6geaDUVEa+CGqQbq1yDfV4Iw+BRdw6MFFRM7BA7EChgoUqyZoZRwnHB10="

    
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true
search_full_content      : true
search_provider          : lunr
#google:
#  search_engine_id       : "018147860991122944355:lwlcgdyuutq"
#  instant_search         : true
# SEO Related
google_site_verification : "Gads1dEJfrM11RlSRBUKWHHjKWkf_JfNOC1Deq7LaF0"

og_image                 : "/assets/images/og_image.jpg"


# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : "Organization"
  name                   : "AnyBody Technology"
  links: 
    linkedin         : "https://www.linkedin.com/company/anybody-technology-a-s"
    github           : "https://github.com/anybody"
    youtube          : "https://www.youtube.com/user/anybodytech"
    facebook         : "https://www.facebook.com/groups/AnyBodyGroup/"

# Analytics
analytics:
  provider               : "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-201751-2"
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "AnyBody Technology"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Experts in Musculoskeletal Modeling and simulations."
  location         : "Aalborg, Denmark"
  email            : "sales@anybodytech.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:sales@anybodytech.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://anybodytech.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/groups/AnyBodyGroup/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/anybody"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/groups/AnyBodyGroup/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: "https://github.com/anybody"
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:


# Reading Files
include:
  - .htaccess
  - _pages
  - CNAME
  - .nojekyll
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: pygments
kramdown:
  input: GFM
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Copenhagen # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  ###- jekyll-github-metadata
  - jekyll-sitemap
  ###- jekyll-mentions
  ###- jekyll-redirect-from
  - jekyll-gist
  - jekyll-feed
  - pygments.rb
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  ###- jekyll-github-metadata
  - jekyll-sitemap
  ###- jekyll-mentions
  ###- jekyll-redirect-from
  - jekyll-gist
  - jekyll-feed
  - pygments.rb
  - jemoji
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
